### ISSUE TITLE
Support the alias of the official registry

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#162]
AS IS

```yaml
registries:
- name: official
  type: github_content
  repo_owner: suzuki-shunsuke
  repo_name: aqua-registry
  ref: v0.1.1-0
  path: registry.yaml
```

TO BE

```yaml
registries:
- type: official
  ref: v0.1.1-0
```
