### ISSUE TITLE
support changing the package metadata per package version

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#21]
The structure of the package may be different per version.

**Comment by suzuki-shunsuke** [comment]
```yaml
  packages:
  - name: jq
    type: github_release
    repo_owner: stedolan
    repo_name: jq
    version_constraint: ">= 1.6"
    asset: 'jq-{{if eq .OS "darwin"}}osx{{else}}{{.OS}}{{end}}-{{.Arch}}'
    files:
    - name: jq
```

```yaml
  packages:
  - name: jq
    type: github_release
    repo_owner: stedolan
    repo_name: jq
    versions:
    - version_constraint: ">= 1.6"
      asset: 'jq-{{if eq .OS "darwin"}}osx{{else}}{{.OS}}{{end}}-{{.Arch}}'
      files:
      - name: jq
```

**Comment by suzuki-shunsuke** [comment]
* https://github.com/hashicorp/go-version
* https://github.com/Masterminds/semver

**Comment by suzuki-shunsuke** [comment]
Problem: Some tools isn't semver.

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/aqua-registry/pull/234#issuecomment-924820966

**Comment by suzuki-shunsuke** [comment]
```yaml
- type: github_release
  repo_owner: golang-migrate
  repo_name: migrate
  asset: 'migrate.{{.OS}}-{{.Arch}}.tar.gz'
  description: Database migrations. CLI and Golang library
  files:
  - name: migrate
    src: 'migrate.{{.OS}}-{{.Arch}}'
  version_constraint: '> 4.14.1'
  version_overrides:
  - version_constraint: '<= 4.14.1'
    asset: 'migrate.tar.gz'
    files:
    - name: migrate
      src: 'migrate'
```
