### ISSUE TITLE
Support goreleaser compatible `replacements`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#245]
https://goreleaser.com/customization/archive/

**Comment by suzuki-shunsuke** [comment]
# e.g. aquasecurity/trivy

https://github.com/aquasecurity/trivy/blob/19c0b70d26134f754b46d6bf6e4a8966a431fd74/goreleaser.yml

```yaml
- name: aquasecurity/trivy
  type: github_release
  repo_owner: aquasecurity
  repo_name: trivy
  link: https://github.com/aquasecurity/trivy
  description: Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues
  goreleaser:
    project_name: trivy
    builds:
    - binary: trivy
    archives:
    - format: tar.gz
      name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
      replacements:
        amd64: 64bit
        386: 32bit
        arm: ARM
        arm64: ARM64
        ppc64le: PPC64LE
        darwin: macOS
        linux: Linux
        openbsd: OpenBSD
        netbsd: NetBSD
        freebsd: FreeBSD
        dragonfly: DragonFlyBSD
```

**Comment by suzuki-shunsuke** [comment]
```yaml
- name: aquasecurity/trivy
  type: github_release
  repo_owner: aquasecurity
  repo_name: trivy
  link: https://github.com/aquasecurity/trivy
  description: Scanner for vulnerabilities in container images, file systems, and Git repositories, as well as for configuration issues
  asset: "trivy_{{.Package.Version}}_{{.Replacements.OS}}-{{.Replacements.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    ppc64le: PPC64LE
    darwin: macOS
    linux: Linux
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD

```
