### ISSUE TITLE
Support `github_content` package

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#260]
e.g.

```yaml
- type: github_content
  repo_owner: suzuki-shunsuke
  repo_name: aqua-installer
  path: aqua-installer
```

```
~/.aqua/pkgs/github_content/github.com/suzuki-shunsuke/aqua-installer/v0.1.3/aqua-installer
AQUA_ROOT/pkgs/github_content/github.com/<repo owner>/<repo name>/<version>/<path>
```
