### ISSUE TITLE
Share configuration across multiple repositories

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#323]
```yaml
imports:
- type: github_content
  repo_owner:
  repo_name:
  path:
  version:
packages:
```

```
~/.aqua/
  pkgs/
  registries/
  imports/
```

The priority of packages when `aqua exec` is run.

1. packages
1. imports
