### ISSUE TITLE
support the syntax `<package name>@<version>`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#332]
AS IS

```yaml
- name: argoproj/argo-rollouts
  registry: standard
  version: v1.0.7 # renovate: depName=argoproj/argo-rollouts
```

TO BE

```yaml
- name: argoproj/argo-rollouts@v1.0.7
  registry: standard
```

You don't have to write code comments for Renovate.
Of course, the attribute `version` is also supported.
