### ISSUE TITLE
support `registry`

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#7]

**Comment by suzuki-shunsuke** [comment]
# Third Party Registry

```yaml
packages:
- name: golangci-lint
  registry: foo
  version: v1.42.0 # renovate: depName=golangci/golangci-lint
registries:
- name: foo
  type: github_content
  repo_owner: suzuki-shunsuke
  repo_name: my-aqua-config
  ref: v0.1.0
  path: aqua.yaml
```

**Comment by suzuki-shunsuke** [comment]
# type: local

```yaml
packages:
- name: golangci-lint
  registry: golang
  version: v1.42.0 # renovate: depName=golangci/golangci-lint
registries:
- name: golang
  type: local
  path: aqua/golang.yaml
```

**Comment by suzuki-shunsuke** [comment]
# type: http

```yaml
packages:
- name: golangci-lint
  registry: golang
  version: v1.42.0 # renovate: depName=golangci/golangci-lint
registries:
- name: golang
  type: http
  url: https://example.com
```
